// <auto-generated />
namespace zenithsociety.Migrations.Events
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ZenithModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZenithModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201610232155085_ZenithModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
